services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: firstpass
      POSTGRES_PASSWORD: password
      POSTGRES_DB: firstpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
